CREATE DATABASE [User];

CREATE TABLE Users (ID INT, Name VARCHAR(100),
	CONSTRAINT PK_UserID PRIMARY KEY(ID)
);
INSERT INTO Users (ID, Name) VALUES(1, 'Oliver Nicholls');

CREATE TABLE UserBasket(UserID INT, BasketID INT,
    CONSTRAINT FK_UserID FOREIGN KEY(UserID) REFERENCES Users(ID)
);
INSERT INTO UserBasket (UserID, BasketID) VALUES(1, 1);